### ISSUE TITLE
PowerShell Core Azure Function cant authenticate using Connect-PowerBIServiceAccount

### ISSUE THREAD

**Issue by schenardie** [microsoft/powerbi-powershell#288]
#### Issue description
Upon trying to authenticate using MicrosoftPowerBIMgmt module it fails  (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)

#### Steps to reproduce the issue

1.  Create Azure Function App Running Powershell Core 7
2. Change requirements.psd1 to add     'MicrosoftPowerBIMgmt' = '1.*'
3. Try to authenticate with Secret or Certificate using 
Connect-PowerBIServiceAccount -ServicePrincipal -CertificateThumbprint "****" -ApplicationId $appid -Tenant $tenant

#### What's the expected result?
Connect to Powerbi Api

#### What's the actual result?
[Error]   ERROR: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)

#### Additional details / screenshot

**Comment by CattieCat** [comment]
Can you confirm which version of MicrosoftPowerBIMgmt you are using?

**Comment by schenardie** [comment]
Hi Cattie. Latest

**Comment by CattieCat** [comment]
Looks like it's a common problem with PowerShell Core according to this thread https://github.com/PowerShell/PowerShell/issues/10473 
However I don't think it's 100% the issue because MicrosoftPowerBIMgmt works well on desktop PowerShell 7.1.0 using service principal and auth by cert. 
![image](https://user-images.githubusercontent.com/6728488/114812401-c4dc6280-9d64-11eb-8708-46a5c5b6a002.png)

We don't have enough resource to dig into this issue with Azure function right now but will get back to you when we have an update.

**Comment by schenardie** [comment]
Hi Cattie, i can confirm it works on my Windows 10 with PWSH 7 as well.

Can this be done on the module?
https://github.com/dotnet/runtime/issues/25044#issuecomment-520203003

Thanks

**Comment by niphlod** [comment]
+1, works locally but not as Powershell 7 function.

**Comment by schenardie** [comment]
Hi Cattie,  not sure if you saw my last comment,  would it be doable to do what is suggested on that comment? 
"So what's the recommended path-forward here? Everyone that used this library rewrites their module to use SHA256.Create()?"

Thanks

**Comment by CattieCat** [comment]
I think so but we'll need to investigate. Some user has done workaround by spinning up the Windows PowerShell 5.1 executable to run Power BI Cmdlets

**Comment by schenardie** [comment]
Thanks for that @CattieCat.

Do you have any references of people doing that on Azure Functions?? Couldn't find much about people invoking Powershell 5.1 via Core from inside of an Azure Function, its not ideal but it could be a temp fix untill the module gets updated.

**Comment by Francisco-Gamino** [comment]
Hello @CattieCat -- I am from the Functions team and I am looking into this issue. May I have your help to continue to investigate this further?

This is the location where the exception is being thrown https://github.com/microsoft/powerbi-powershell/blob/dev/src/Common/Common.Authentication/WindowsAuthenticationFactory.cs#L49

![image](https://user-images.githubusercontent.com/12720858/117081297-78959a00-acf4-11eb-93f9-eb908c0b7fcc.png)

This issue does not repro locally (on PS 5.1 or PSCore 7); it only repros in the Azure Functions service. In the Functions service we run PowerShell 7.0.6. Please let me know if you have a time today or tomorrow to sync on this. Thank you.

**Comment by Francisco-Gamino** [comment]
cc: @AnatoliB @anirudhgarg

**Comment by niphlod** [comment]
@schenardie : this is a relevant snippet for the workaround

```
$modulePath = $Env:APPSETTING_POWERBI_PROFILE_MODULE_PATH
Import-Module $modulePath -usewindowspowershell -warningaction silentlycontinue

...
Connect-PowerBIServiceAccount -Credential $credential
$token = Get-PowerBIAccessToken
....
$headers = @{ "Authorization" = $token["Authorization"] }
 
# Power BI API call
$apihost = $Env:APPSETTING_POWERBI_API_HOST
$uri = $apihost + "groups/$workspaceID/datasets/$datasetID/refreshes"
 
Invoke-RestMethod -Uri $uri -Headers $headers -Method Post -erroraction stop
```
it's a "horrible" workaround because Connect-PowerBIServiceAccount only works in PS5, hence the `usewindowspowershell` in the import.
But, any other call that effectively tries to reach the api errors out (probably because serialization of some rich object fails between PS7 and PS5).
One good thing about the whole ordeal is that you can at least pass around the token (which is a simple string) and then craft an invoke-restmethod "manually".

Kudos to @GabrielePagani for having the patience to ironing things out while finding all of those things by trial and error.

That being said, it'd be best that Connect-* works oob with PS7 even in Azure Functions so we can all benefit from the entire module ;-)

**Comment by CattieCat** [comment]
Following up with @Francisco-Gamino  offline.
Guys, notice ahead, there will probably not be fast fix for this because we are seriously lack of resource on this.

**Comment by furmangg** [comment]
I do hope Microsoft can resolve the root cause so crazy workarounds aren't necessary. The workaround we used in Azure Functions is spinning up the Powershell 5.1 powershell.exe like this:

```

$ErrorActionPreference = "Stop";

try
{
	$UserName = (Get-AzKeyVaultSecret -vaultName $env:KeyVaultName -name $env:KeyVaultSecretNameAuditLogUsername).SecretValueText
	$PlainPassword = (Get-AzKeyVaultSecret -vaultName $env:KeyVaultName -name $env:KeyVaultSecretNameAuditLogPassword).SecretValueText
	$SecurePassword = $PlainPassword | ConvertTo-SecureString -AsPlainText -Force
	$UserCredential = New-Object System.Management.Automation.PSCredential -ArgumentList $UserName, $SecurePassword

	$env:UserName = $UserName;
	$env:PlainPassword = $PlainPassword;

    $script = { 
        $ErrorActionPreference = "Stop";
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

        $UserName = $env:UserName;
        $PlainPassword = $env:PlainPassword;
        $SecurePassword = $PlainPassword | ConvertTo-SecureString -AsPlainText -Force
        $UserCredential = New-Object System.Management.Automation.PSCredential -ArgumentList $UserName, $SecurePassword

        Login-PowerBI -Credential $UserCredential -ServicePrincipal -Tenant $env:TenantId 


        #do whatever like Get-PowerBIActivityEvent
        
    }
        
    #Login-PowerBI is failing with this error under PowerShell Core 7 so working around by running PowerShell 5: https://docs.microsoft.com/en-us/answers/questions/339901/34could-not-load-type-39systemsecuritycryptography.html
    $PowerShell64bitPath = Get-ChildItem -Path $Env:Windir\WinSxS | Where-Object {$_.FullName -match "amd64_microsoft-windows-powershell-exe"}
    $PowerShell64bitPath = Get-ChildItem -Path $PowerShell64bitPath.FullName -Filter PowerShell.exe | Select-Object -ExpandProperty FullName
    & $PowerShell64bitPath -NoLogo -NoProfile -WindowStyle Hidden -NonInteractive -Command $Script

}
catch {
    "Failed!"
    throw $_
}
```

**Comment by CattieCat** [comment]
We have verified that moving to MSAL with some additional changes solves the issue with Azure Functions. Plan to release the change ~1 month.

**Comment by Francisco-Gamino** [comment]
Thank you @CattieCat for your help to investigate this issue. I will share this information with our customers.

**Comment by mattdavis20** [comment]
> I do hope Microsoft can resolve the root cause so crazy workarounds aren't necessary. The workaround we used in Azure Functions is spinning up the Powershell 5.1 powershell.exe like this:
> 
> ```
> 
> $ErrorActionPreference = "Stop";
> 
> try
> {
>     $UserName = (Get-AzKeyVaultSecret -vaultName $env:KeyVaultName -name $env:KeyVaultSecretNameAuditLogUsername).SecretValueText
>     $PlainPassword = (Get-AzKeyVaultSecret -vaultName $env:KeyVaultName -name $env:KeyVaultSecretNameAuditLogPassword).SecretValueText
>     $SecurePassword = $PlainPassword | ConvertTo-SecureString -AsPlainText -Force
>     $UserCredential = New-Object System.Management.Automation.PSCredential -ArgumentList $UserName, $SecurePassword
> 
>     $env:UserName = $UserName;
>     $env:PlainPassword = $PlainPassword;
> 
>     $script = { 
>         $ErrorActionPreference = "Stop";
>         [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
> 
>         $UserName = $env:UserName;
>         $PlainPassword = $env:PlainPassword;
>         $SecurePassword = $PlainPassword | ConvertTo-SecureString -AsPlainText -Force
>         $UserCredential = New-Object System.Management.Automation.PSCredential -ArgumentList $UserName, $SecurePassword
> 
>         Login-PowerBI -Credential $UserCredential -ServicePrincipal -Tenant $env:TenantId 
> 
> 
>         #do whatever like Get-PowerBIActivityEvent
> 
>         "Success" #don't do Write-Host "Success"
>         
>     }
>         
>     #Login-PowerBI is failing with this error under PowerShell Core 7 so working around by running PowerShell 5: https://docs.microsoft.com/en-us/answers/questions/339901/34could-not-load-type-39systemsecuritycryptography.html
>     $PowerShell64bitPath = Get-ChildItem -Path $Env:Windir\WinSxS | Where-Object {$_.FullName -match "amd64_microsoft-windows-powershell-exe"}
>     $PowerShell64bitPath = Get-ChildItem -Path $PowerShell64bitPath.FullName -Filter PowerShell.exe | Select-Object -ExpandProperty FullName
>     & $PowerShell64bitPath -NoLogo -NoProfile -WindowStyle Hidden -NonInteractive -OutputFormat Text -Command $Script
> 
> }
> catch {
>     "Failed!"
>     throw $_
> }
> ```
> 
> I had a few Write-Host statements in there that seemed to cause problems locking stdout or something. See the Write-Host comment.

I am curious if `Invoke-PowerBIRestMethod` is a command that others have used in the `$script` portion of their code.  It has not run successfully for me with these workarounds.

**Comment by furmangg** [comment]
Works for me @mattdavis20. I assume you did a Login-PowerBI in the script block?

Want to share your code so we can see if we spot a problem?

**Comment by mattdavis20** [comment]
Below is the run.ps1 script.
```
using namespace System.Net
using namespace Microsoft.PowerShell.Utility

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

# Write to the Azure Functions log stream.
Write-Host "PowerShell HTTP trigger function processed a request."

# $ErrorActionPreference = "Stop";

# Interact with query parameters or the body of the request.
$Azure_username = $Request.Body.Azure_username
$Azure_password = $Request.Body.Azure_password
$GatewayID = $Request.Body.GatewayID
$DatasourceID = $Request.Body.DatasourceID
$Modulus = $Request.Body.Modulus
$Exponent = $Request.Body.Exponent
$Update_user = $Request.Body.Update_user
$Update_password = $Request.Body.Update_password

$out = $null

try {
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    # $pbipath = 'D:\home\site\wwwroot\Modules\Microsoft.PowerBI.Api.3.18.1\lib\netstandard2.0\Microsoft.PowerBI.Api.dll'
    $pbipath = 'C:\Users\n1520720\OneDrive - Liberty Mutual\Codalak Project\Codalak Repositories\AzurePowerShellFunctions\CdlkSPIFunc\Modules\Microsoft.PowerBI.Api.3.18.1\lib\netstandard2.0\Microsoft.PowerBI.Api.dll'
    [System.Reflection.Assembly]::LoadFrom($pbipath)

    Import-Module MicrosoftPowerBIMgmt
    Import-Module MicrosoftPowerBIMgmt.Profile

    # Create a public key with the exponent and modulus from the gateway datasource information
    $gatewayPublicKey = @{
        exponent = $Exponent;
        modulus = $Modulus
    }

    # Encryption process which utilizes the PowerBI API
    $gatewayKeyObj = [Microsoft.PowerBI.Api.Models.GatewayPublicKey]::new($gatewayPublicKey.exponent, $gatewayPublicKey.modulus)
    $basicCreds = [Microsoft.PowerBI.Api.Models.Credentials.BasicCredentials]::new($Update_user, $Update_password)
    $credentialsEncryptor = [Microsoft.PowerBI.Api.Extensions.AsymmetricKeyEncryptor]::new($gatewayKeyObj)

    $credentialDetails = [Microsoft.PowerBI.Api.Models.CredentialDetails]::new(
            $basicCreds, 
            [Microsoft.PowerBI.Api.Models.PrivacyLevel]::Private, 
            [Microsoft.PowerBI.Api.Models.EncryptedConnection]::Encrypted, 
            $credentialsEncryptor)

    # Construct the body for the request.
    $body = @{
        credentialDetails = @{
            credentialType      = "Basic";
            credentials         = $credentialDetails.Credentials;
            encryptedConnection = "Encrypted";
            encryptionAlgorithm = "RSA-OAEP";
            useEndUserOAuth2Credentials = "False"
            privacyLevel        = "Organizational";
            }
        }

    $relativeUrlPath = "gateways/" + $GatewayID + "/datasources/" + $DatasourceID

    $env:Azure_username = $Azure_username;
    $env:Azure_PlainPassword = $Azure_password;
    $env:PBIbody = $body;
    $env:InvokeURL = $relativeUrlPath;

    $Script = {
        
        $PbiBody = $env:PBIbody;
        $PBIInvokeURL = $env:InvokeURL;
        $azure_username = $env:Azure_username;
        $azure_PlainPassword = $env:Azure_PlainPassword;
        $azure_SecurePassword = $env:azure_plainPassword | ConvertTo-SecureString -AsPlainText -Force
        
        # Attempting to Connect to PowerBI
        $credential = New-Object System.Management.Automation.PSCredential -ArgumentList $azure_username, $azure_SecurePassword
        Login-PowerBI -Credential $credential        
        
        # The error kicks back here:
        Invoke-PowerBIRestMethod -Url $PBIInvokeURL -Method PATCH -Verbose -Body ($PbiBody | ConvertTo-Json)
        
        Logout-PowerBI

    }

    #Login-PowerBI is failing with this error under PowerShell Core 7 so working around by running PowerShell 5: https://docs.microsoft.com/en-us/answers/questions/339901/34could-not-load-type-39systemsecuritycryptography.html
    $PowerShell64bitPath = Get-ChildItem -Path $Env:Windir\WinSxS | Where-Object {$_.FullName -match "amd64_microsoft-windows-powershell-exe"}
    $PowerShell64bitPath = Get-ChildItem -Path $PowerShell64bitPath.FullName -Filter PowerShell.exe | Select-Object -ExpandProperty FullName
    $out = & $PowerShell64bitPath -NoLogo -NoProfile -WindowStyle Hidden -NonInteractive -OutputFormat Text -Command $Script
    
    # Invoke-PowerBIRestMethod -Url $InvokeURL -Method PATCH -Verbose -Body ($PBIbody | ConvertTo-Json)

    Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
        StatusCode = [HttpStatusCode]::OK
        Body       = $out
    })

}
catch {
    Write-Verbose "Error Running Something"
    $ErrorMessage = $_.Exception.Message
    $body = ($ErrorMessage | ConvertTo-Json)
}
```

**Comment by furmangg** [comment]
Is it the Invoke-PowerBIRestMethod inside or outside the script block which errors out? Are you sure?

**Comment by furmangg** [comment]
I would try converting the body to JSON before you write it to the environment variable. And I would print it out inside the script block to ensure you for the whole contents of the body. Just a guess.

**Comment by mattdavis20** [comment]
Good call on converting it to JSON prior to passing it into the script as that was the issue.  Thank you for the extra set of eyes!

**Comment by mattdavis20** [comment]
So after testing out locally via VS Code, I can mock the function and hit the url (i.e. http://localhost:7071/api/CdlkSPIFunc) and it works as expected.  However, deploying to Azure and testing via the console, I get a 204 response.  My guess is that the response of the function is returning some null lines, which are immediately triggering the 204 response?  Any way I can silence null items in the response?

**Comment by schenardie** [comment]
Hi @CattieCat 
Is this issue on the line for fix anytime soon??  

Thanks

**Comment by khouloudbelhaj** [comment]
Is there any update on this issue?

**Comment by CattieCat** [comment]
We've verified using MSAL instead of ADAL resolves the issue. Change
targets release by 6/18

**Comment by CattieCat** [comment]
It's an incompatibility issue between ADAL and powershell core. Not sure
why it doesn't repro on the local powershell core but on Azure Functions.
Previous messages in this thread should have reference to corresponding
discussions.

**Comment by khouloudbelhaj** [comment]
@CattieCat  : ok thank you Cattie, I will try using MSAL as an alternative.

**Comment by khouloudbelhaj** [comment]
@Francisco-Gamino  : Do you have any idea how much time it will take to be resolved ( the issue related to azure functions)

**Comment by Francisco-Gamino** [comment]
Hello @khouloudbelhaj -- @CattieCat is working on the fix, which is in the MicrosoftPowerBIMgmt module. The ETA is 6/18/21

**Comment by khouloudbelhaj** [comment]
@Francesco-Manni  Great News!

**Comment by khouloudbelhaj** [comment]
@Francisco-Gamino : How this update will be implement in azure functions and what will be the version used to call the module MicrosoftPowerBIMgmt 
?

**Comment by Francisco-Gamino** [comment]
Thanks @CattieCat fixing this issue. 

The fix is available at https://www.powershellgallery.com/packages/MicrosoftPowerBIMgmt/1.2.0. Please update your function app to use this module. 

If you are uploading the `MicrosoftPowerBIMgmt` module with your function app content, download the latest version to your `<functionAppRoot>\Modules\...` folder and republish your function app. Alternatively, you can use Managed Dependencies to install the latest module. For more information, please see https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell?tabs=portal#dependency-management.

**Comment by mattdavis20** [comment]
That fix has put our Azure Function back on track. Thank you for addressing the issue!

**Comment by manipuraco** [comment]
we are experiencing similar issue with MSOL in azure functions. Works ok with PS Core 7, but due to a de-serialization issue there, we need to move this to run as per below. I keep getting 
_Program 'powershell.exe' failed to run: StandardOutputEncoding is only supported when standard output is redirected._ 
and cant figure out where the bug is. 
script attached for reference. would appreciate is someone can provide some resolution.

`using namespace System.Net
# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)
# Write to the Azure Functions log stream.
Write-Host "PowerShell HTTP trigger function processed a request."
# Script to run with PowerShell.exe
$z=@([System.Web.HttpUtility]::UrlDecode($Request.Query.Delegatedadminid),[System.Web.HttpUtility]::UrlDecode($Request.Query.refreshToken),[System.Web.HttpUtility]::UrlDecode($Request.Query.TeantWithLicenses),[System.Web.HttpUtility]::UrlDecode($Request.Query.Tenants),[System.Web.HttpUtility]::UrlDecode($Request.Query.FilterDetails),[System.Web.HttpUtility]::UrlDecode($Request.Query.userid),[System.Web.HttpUtility]::UrlDecode($Request.Query.client_id),[System.Web.HttpUtility]::UrlDecode($Request.Query.client_secret),[System.Web.HttpUtility]::UrlDecode($Request.Query.switch_exclude))
$Script = {
    param (
        [string]$a,[string]$b,[string]$c,[string]$d,[string]$e,[string]$f,[string]$g,[string]$h,[string]$i
    )
	
	Import-Module MsOnline
	Import-Module PartnerCenter
    $_Delegatedadminid = $a
    $_refreshToken = $b
    $_TeantWithLicenses = $c 
    $_Tenants = $d
    $_FilterDetails = $e 
    $_userid = $f
    $_client_id = $g 
    $_client_secret = $h 
    $_switch_exclude = $i

    #!/bin/sh
    $Delegatedadminid = $_Delegatedadminid
    $refreshToken = $_refreshToken
    $TeantWithLicenses = $_TeantWithLicenses | ConvertFrom-Json
    $Tenants = $_Tenants
    $FilterDetails = $_FilterDetails | ConvertFrom-Json
    $userid = $_userid
    $client_id = $_client_id
    $client_secret = $_client_secret
    $switch_exclude = $_switch_exclude
    $secpasswd = ConvertTo-SecureString $client_secret -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential ($client_id, $secpasswd)

    # $refreshToken = <refreshtoken>
    #Get access tokens from refreshtoken
    #$token = New-PartnerAccessToken -ApplicationId $client_Id -Credential $credential -RefreshToken $refreshToken -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ServicePrincipal -Tenant $Delegatedadminid
    $aadGraphToken = New-PartnerAccessToken -ApplicationId $client_Id -Credential $credential -RefreshToken $refreshToken -Scopes 'https://graph.windows.net/.default' -ServicePrincipal -Tenant $Delegatedadminid
    $graphToken = New-PartnerAccessToken -ApplicationId $client_Id -Credential $credential -RefreshToken $refreshToken -Scopes 'https://graph.microsoft.com/.default' -ServicePrincipal -Tenant $Delegatedadminid

    Connect-MsolService -AdGraphAccessToken $aadGraphToken.AccessToken -MsGraphAccessToken $graphToken.AccessToken
    $UserNameResults = @()

    foreach($tenantID in $Tenants){
        $licenseNames = $TeantWithLicenses.$tenantID
        foreach($licenseName in $licenseNames){
            $getTenantID = $tenantID.split('_EXPLODE_',[System.StringSplitOptions]::RemoveEmptyEntries)
            $getUserTenantID = $getTenantID[0]
            $FilterID = $getTenantID[1]
            
            IF($FilterDetails.$tenantID){
                $office = $FilterDetails.$tenantID.office_filter
                $country = $FilterDetails.$tenantID.country_filter
                $state = $FilterDetails.$tenantID.state_filter
                $city = $FilterDetails.$tenantID.city_filter
                
                IF(-not ($FilterDetails.$tenantID.excludeLicense -contains $licenseName)){
                    If ($office -and $country -and $city -and $state){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -ne $office -and $_.country -ne $country -and $_.city -ne $city -and $_.state -ne $state} | Sort-Object DisplayName
                        }Else{
                                $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -eq $office -and $_.country -eq $country -and $_.city -eq $city -and $_.state -eq $state} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($office -and $country -and $city){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -ne $office -and $_.country -ne $country -and $_.city -ne $city} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -eq $office -and $_.country -eq $country -and $_.city -eq $city} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($office -and $country -and $state){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -ne $office -and $_.country -ne $country -and $_.state -ne $state} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -eq $office -and $_.country -eq $country -and $_.state -eq $state} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($office -and $city -and $state){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -ne $office -and $_.city -ne $city -and $_.state -ne $state} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -eq $office -and $_.city -eq $city -and $_.state -eq $state} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($country -and $city -and $state){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.country -ne $country -and $_.city -ne $city -and $_.state -ne $state} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.country -eq $country -and $_.city -eq $city -and $_.state -eq $state} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($office -and $country){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -ne $office -and $_.country -ne $country} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -eq $office -and $_.country -eq $country} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($office -and $city){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -ne $office -and $_.city -ne $city} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -eq $office -and $_.city -eq $city} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($office -and $state){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -ne $office -and $_.state -ne $state} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -eq $office -and $_.state -eq $state} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($city -and $state){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.city -ne $city -and $_.state -ne $state} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.city -eq $city -and $_.state -eq $state} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($country -and $state){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.country -ne $country -and $_.state -ne $state} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.country -eq $country -and $_.state -eq $state} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($country -and $city){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.country -ne $country -and $_.city -ne $city} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.country -eq $country -and $_.city -eq $city} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($office){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -ne $office} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.office -eq $office} | Sort-Object DisplayName
                        }
                        
                    }ElseIf ($country){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.country -ne $country} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.country -eq $country} | Sort-Object DisplayName
                        }
                    } 
                    ElseIf ($city){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.city -ne $city} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.city -eq $city} | Sort-Object DisplayName
                        }
                    }
                    ElseIf ($state){
                        If($switch_exclude -eq 1){
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.state -ne $state} | Sort-Object DisplayName
                        }Else{
                            $UserNames = Get-MsolUser -TenantId $getUserTenantID -All | Where-Object {($_.licenses).AccountSkuId -like "*$($licenseName)" -and $_.state -eq $state} | Sort-Object DisplayName
                        }
                    }
                    }
                }Else{
                $UserNames = Get-MsolUser -TenantId $getUserTenantID -ALL | Where-Object {($_.licenses).AccountSkuId -ilike "*$($licenseName)"} | Sort-Object DisplayName
            }
            # echo $UserNames
            foreach ($licenseUserName in $UserNames){
                $UserNameProperty = @{
                    userID = $userid
                    UserPrincipalName = $licenseUserName.UserPrincipalName
                    DisplayName = $licenseUserName.DisplayName
                    isLicensed = $licenseUserName.isLicensed
                    LicenseName = $licenseName
                    TenantID = $getUserTenantID
                    FilterID = $FilterID
                }
                $UserNameResults += New-Object psobject -Property $UserNameProperty
            }
        }
    }
    $UserNameResults
}
# Run using PowerShell.exe instead of using PowerShell 6
$64bitPowerShellPath = Get-ChildItem -Path $Env:Windir\WinSxS -Filter PowerShell.exe -Recurse -ErrorAction SilentlyContinue | Where-Object {$_.FullName -match "amd64"}
$env:64bitPowerShellPath=$64bitPowerShellPath.VersionInfo.FileName
$scriptResult = &$env:64bitPowerShellPath -WindowStyle Hidden -NonInteractive -OutputFormat Text -Command $Script -args $z

# Associate values to output bindings by calling 'Push-OutputBinding'.
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    headers = @{'content-type'='application\json'}
    StatusCode = [HttpStatusCode]::OK
    Body = $scriptResult | Select-Object userID,UserPrincipalName,DisplayName,isLicensed,LicenseName,TenantID,FilterID | ConvertTo-Json
})`

**Comment by Francisco-Gamino** [comment]
Hello @manipuraco -- could you please open an issue at https://github.com/Azure/azure-functions-powershell-worker ? Thanks.

**Comment by furmangg** [comment]
@CattieCat We are still seeing this error on "Login-PowerBI -Credential $UserCredential" when the user is an on-prem AD user which has been synced to the cloud running in PowerShell Core 7. The error is below. So it appears that somewhere in some branch of the code is still trying to use SHA256Cng which isn't supported in .NET core. I'm not sure if it's the Power BI PowerShell cmdlets or in some library you don't own. This it tested with the latest Power BI PowerShell cmdlets v1.2.1077.0.

We are not seeing this error using a cloud-only user account.

One or more errors occurred. (Error Acquiring Token: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.) Exception : Type : System.AggregateException InnerExceptions : Type : System.Security.Authentication.AuthenticationException TargetSite : Name : MoveNext DeclaringType : Microsoft.PowerBI.Common.Authentication.WindowsAuthenticationFactory+<HandleAuthentication>d__3, Microsoft.PowerBI.Common.Authentication, Version=1.2.1077.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 MemberType : Method Module : Microsoft.PowerBI.Common.Authentication.dll StackTrace : at Microsoft.PowerBI.Common.Authentication.WindowsAuthenticationFactory.HandleAuthentication(IPowerBIEnvironment environment, IPowerBILogger logger, IPowerBISettings settings, IDictionary`2 queryParameters, String userName, SecureString password) at Microsoft.PowerBI.Common.Authentication.WindowsAuthenticationFactory.Authenticate(IPowerBIEnvironment environment, IPowerBILogger logger, IPowerBISettings settings, String userName, SecureString password) at Microsoft.PowerBI.Commands.Common.AuthenticationFactorySelector.Authenticate(IPowerBIEnvironment environment, IPowerBILogger logger, IPowerBISettings settings, String userName, SecureString password) Message : Error Acquiring Token: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Source : Microsoft.PowerBI.Common.Authentication HResult : -2146233087 Message : One or more errors occurred. (Error Acquiring Token: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.) TargetSite : Name : ThrowIfExceptional DeclaringType : System.Threading.Tasks.Task MemberType : Method Module : System.Private.CoreLib.dll StackTrace : at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Microsoft.PowerBI.Commands.Profile.ConnectPowerBIServiceAccount.ExecuteCmdlet() at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord() InnerException : Type : System.Security.Authentication.AuthenticationException TargetSite : Name : MoveNext DeclaringType : Microsoft.PowerBI.Common.Authentication.WindowsAuthenticationFactory+<HandleAuthentication>d__3, Microsoft.PowerBI.Common.Authentication, Version=1.2.1077.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 MemberType : Method Module : Microsoft.PowerBI.Common.Authentication.dll StackTrace : at Microsoft.PowerBI.Common.Authentication.WindowsAuthenticationFactory.HandleAuthentication(IPowerBIEnvironment environment, IPowerBILogger logger, IPowerBISettings settings, IDictionary`2 queryParameters, String userName, SecureString password) at Microsoft.PowerBI.Common.Authentication.WindowsAuthenticationFactory.Authenticate(IPowerBIEnvironment environment, IPowerBILogger logger, IPowerBISettings settings, String userName, SecureString password) at Microsoft.PowerBI.Commands.Common.AuthenticationFactorySelector.Authenticate(IPowerBIEnvironment environment, IPowerBILogger logger, IPowerBISettings settings, String userName, SecureString password) Message : Error Acquiring Token: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Source : Microsoft.PowerBI.Common.Authentication HResult : -2146233087 Source : System.Private.CoreLib HResult : -2146233088 TargetObject : Microsoft.PowerBI.Commands.Profile.ConnectPowerBIServiceAccount CategoryInfo : WriteError: (Microsoft.PowerBI.C…werBIServiceAccount:ConnectPowerBIServiceAccount) [Connect-PowerBIServiceAccount], AggregateException FullyQualifiedErrorId : One or more errors occurred. (Error Acquiring Token: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.),Microsoft.PowerBI.Commands.Profile.ConnectPowerBIServiceAccount InvocationInfo : MyCommand : Connect-PowerBIServiceAccount

**Comment by CattieCat** [comment]
Thanks for the detail @furmangg. I don't have a clue yet but follow up with other teams to see what could be the difference. Can you help to describe how you run login with on-prem user? Is it local or in Azure Automation?

**Comment by furmangg** [comment]
@CattieCat logging on with an on prem user synced to the cloud looks the same in PowerShell. “ Login-PowerBI -Credential $UserCredential” The difference under the covers is that it authenticates with ADFS or other federation instead of just AAD. Reach out if you have other questions or can’t reproduce. 

I did confirm that no MFA is enabled for that on prem user. 

This isn’t blocking us since we switched to a cloud only user. But I wanted to report.

**Comment by GabrielePagani** [comment]
HI @CattieCat,

starting from few days ago, I'm still facing the issue on "Connect-PowerBIServiceAccount -Credential $credential" after it was fixed on Jun 18, 2021, as Francisco-Gamino commented, and it was working well.

The error message is still "One or more errors occurred. (Error Acquiring Token:Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)"

Something changed?

Thanks in advance.

**Comment by hagrrwal** [comment]
Hi @CattieCat **+1 for getting below error.**
PowerBi Module version: 1.2.1077.0
AZ function Runtime version: ~3
PowerShell Core Version: 7.0
Platform: 32 Bit
The error message is: One or more errors occurred. (Error Acquiring Token:Could not load type 'System.Security.Cryptography.SHA256Cng'
